FROM ubuntu:22.04

# install miniconda
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# install
RUN conda env create -n lorikeet lorikeet-genome'>='LORIKEET_VERSION

# activate the environment
RUN echo "source activate lorikeet" > ~/.bashrc
ENV PATH=$CONDA_DIR/envs/lorikeet/bin:$PATH
